[package]
name = "core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.4"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
